version: '3.8'

services:
  backend:
    image: rupalibansal/backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

  frontend:
    image: rupalibansal/frontend:latest
    ports:
      - "80:5173"